debug info for nla requests, frame init can be with high res and custom DEM, including ssh tunneling (needed for ARC4 connection to LiCSInfo db in JASMIN), function to export eq info to txt (for vis)

diff --git a/bin/orig/LiCSAR_01_mk_crop_extDEM b/bin/orig/LiCSAR_01_mk_crop_extDEM
--- a/bin/orig/LiCSAR_01_mk_crop_extDEM
+++ b/bin/orig/LiCSAR_01_mk_crop_extDEM
@@ -7,31 +7,46 @@
 # Date: 2015/10/26
 # Last revision: 2016/01/25 [add parsing arguments]
 # Last revision: 2016/01/25 [add recreate argument]
+# Last revision: 2020/04/07 [add custom DEM] ML
 #################################################################
   
 # Parsing input [Check number of input arguments, and dump help if not correct]
-USAGE="$0: DEM/dem_crop [recreate=1]" 
+USAGE="$0: DEM/dem_crop [recreate=1] [customdem=/path/to/demtif]]" 
 if [ $# -lt 1 ]; then echo -e "Error: Name of DEM needed.\n$USAGE" >&2; exit 1; fi
-if [ $# -gt 2 ]; then echo -e "Error: Only two arguments maximum.\n$USAGE" >&2; exit 1; fi
+if [ $# -gt 3 ]; then echo -e "Error: Only three arguments maximum.\n$USAGE" >&2; exit 1; fi
 dem=$1
 recreate=$2
+customdem=$3
 
 function mainfunc(){
   local dem=$1
   local recreate=$2
-
-  # Create a crop of DEM for the area to cover all SLCs
+  local customdem=$3
   echo " Running doDEMcrop step (01_doDEMcrop.log)"
-  if [ ! -e "${dem}.dem" ] ; then
+  if [ ! -z $customdem ]; then
+   echo "processing custom DEM"
+   echo "(this routine does not crop the DEM)"
+   mkdir DEM 2>/dev/null
+   #here a workaround to preserve zero values
+   gdal_calc.py -A $customdem --calc='(A==0)*32000+(A!=0)*A' --outfile=temp_customdem.tif --NoDataValue=-32768 >/dev/null 2>/dev/null
+   srtm2dem temp_customdem.tif $dem.dem ${dem}.dem_par 0 -
+   wid=`grep "width:" $dem.dem_par | gawk {'print $2'}`
+   replace_values ${dem}.dem 32000 0.01 temp_customdem $wid 0 2
+   mv temp_customdem ${dem}.dem
+   rm temp_customdem.tif srtm2dem.log 2>/dev/null
+  else
+   # Create a crop of DEM for the area to cover all SLCs
+   if [ ! -e "${dem}.dem" ] ; then
     echo "   Creating external DEM ... "
     mk_dem $dem 1 > 01_doDEMcrop.log 
-  else
+   else
     if [ "$recreate" == "1" ]; then
       echo "   Recreating external DEM ... "
       mk_dem $dem 1 > 01_doDEMcrop.log 
     else
       echo "   DEM already exists [force create again by using option recreate=1 ] "
     fi
+   fi
   fi
 }
 
@@ -77,7 +92,9 @@ function mk_dem(){
   if [ ! -d "DEM" ]; then mkdir DEM; fi
   # Branching here to select SRTM or GDEM
   #if [ ${latmin} -lt "60.0" || ${latmax} -lt "-56.0" ]; then # #if [ ${latmin} > "60.0" ]; then #
-  if [ `echo $latmin'<'60.0 | bc -l` == 0 ]; then
+  #strange... this was here:
+  #if [ `echo $latmin'<'60.0 | bc -l` == 0 ]; then
+  if [ `echo $latmax'<'60.0 | bc -l` == 0 ]; then
     echo "USE make_gdem2insar [some files might not exist. It could not be a problem...]"
     mk_gdem2insar $dem $lonmin $lonmax $latmin $latmax #> /dev/null 2>&1
   else
@@ -92,4 +109,4 @@ function mk_dem(){
   
 }
 
-mainfunc $dem $recreate
+mainfunc $dem $recreate $customdem
